---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: ospcloud
  register: result

- debug:
    var: "{{ result.openstack_servers }}"

# - name: Delete instances
  
