---
# tasks file for roles/osp-instance-delete
- name: fetch instance info
  os_server_facts:
    cloud: ospcloud
  register: result

- name: openstack server info
  debug:
    var: "{{ result }}"

# - name: Delete instances
  
