---
# tasks file for roles/osp-instance-delete
- name: fetch instance info
  os_server_info:
    cloud: ospcloud
  register: result

- name: openstack server info
  debug:
    var: "{{ result.openstack_servers }}"

# - name: Delete instances
  
