---
# tasks file for roles/osp-instance-delete
- name: fetch instance info
  os_server_facts:
    cloud: ospcloud
  register: result

- name: openstack server info
  debug:
    var: openstack_servers

- name: delete instances
  os_server:
    name: "{{ item.hostname }}"
    state: absent
  loop: "{{ openstack_servers }}"