# Playbook to setup workstation as isolated node and create osp network, router, SG and ssh keypair
- hosts: workstation
  become: yes
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml 

