---
- name: install HAProxy
  yum:
    name: haproxy
    state: latest

- name: enable HAProxy
  service:
    name: haproxy
    enabled: true
    state: started

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy