---
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    state: present
    name: "{{ item.name }}.example.opentlc.com"
    image: rhel-guest
    key_name: ansible_ssh
    timeout: 200
    flavor: m2.small
    network: "{{ item.network_name }}"
    meta:
      hostname: "{{ item.name }}.example.opentlc.com"
  loop:
    - {name: frontend1, network_name: int_network }
    - {name: app1, network_name: int_network }
    - {name: app2, network_name: int_network }
    - {name: appdb1, network_name: int_network }

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    server: "{{ item }}.example.opentlc.com"
  loop:
    - frontend1
    - app1
    - app2
    - appdb1

# - name: Wait for servers to be available
#   wait_for_connection:
#   loop:
#     - frontend1
#     - app1
#     - app2
#     - appdb1