---
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    state: "{{ item.value.state }}"
    name: "{{ item.value.name }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    flavor: "{{ item.value.flavor }}"
    security_groups: "{{ item.value.security_group }}"
    network: int_network
    userdata: |
      {%- raw -%}#!/bin/bash
      echo 
      {% endraw %}
    meta: "{{ item.value.meta[0] }}"
  with_dict: "{{ osp_servers }}"

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    server: "{{ item.value.name }}"
    network: ext_network
    reuse: yes
    wait: yes
    state: present
  with_dict: "{{ osp_servers }}"
  register: osp_floating_ip

- name: Floating IPs
  debug:
    var: "{{ item.floating_ip.floating_ip_address }}"
  with_items: "{{osp_floating_ip.results}}"

- name: wait until instances are SSH ready
  wait_for:
    port: 22
    host: "{{ item.floating_ip.floating_ip_address }}"
    search_regex: OpenSSH
    delay: 5
    timeout: 30
  with_items: "{{osp_floating_ip.results}}"