---
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    state: "{{ item.value.state }}"
    name: "{{ item.value.name }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    flavor: "{{ item.value.flavor }}"
    security_groups: "{{ item.value.security_group }}"
    network: int_network
    meta: "{{ item.value.meta[0] }}"
  with_dict: "{{ osp_servers }}"

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    server: "{{ item.value.name }}"
    network: ext_network
    reuse: yes
    wait: yes
    state: present
  with_dict: "{{ osp_servers }}"
  register: osp_floating_ip

- name: Floating IPs
  debug:
    var: osp_floating_ip

# - name: Wait for servers to be available
#   wait_for:
#     port: 22
#     host: "{{item.accessIPv4}}"
#     search_regex: OpenSSH
#     delay: 10
#   with_items: "{{osp_facts.ansible_facts.openstack_servers}}"
#   delegate_to: "{{ inventory_hostname }}"