---
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    state: "{{ item.value.state }}"
    name: "{{ item.value.name }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    flavor: "{{ item.value.flavor }}"
    security_groups: "{{ item.value.security_group }}"
    network: int_network
    meta: "{{ item.value.meta[0] }}"
  with_dict: "{{ osp_servers }}"

- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    server: "{{ item.value.name }}"
    network: ext_network
    reuse: yes
    wait: yes
    state: present
  with_dict: "{{ osp_servers }}"
  register: osp_floating_ip

- name: SSH Ready
  command: >
    "ssh -i /root/.ssh/test_id_rsa cloud-user@{{ item.floating_ip.floating_ip_address }} exit; wait; echo $?"
  with_items: "{{osp_floating_ip.results}}"
  register: result
  until: result.rc == 0
  retries: 5
  delay: 10